# размеры окна
WIDTH = 800
HEIGHT = 600

# фпс
FPS = 60

# для текста
TEXT_COLOR = (0,0,0)
FONT_SIZE = 60
TEXT_X = (WIDTH - FONT_SIZE) // 2 - 84
TEXT_Y = HEIGHT // 2 - 65


# для платформы
PLATFORM_COLOR = (0,0,0)
PLATFORM_WIDTH = 100
PLATFORM_HEIGHT = 10
PLATFORM_SPEED = 360
PLATFORM_BUTTOM_OFFSET = 20

# для мяча
BALL_RADIUS = 10
BALL_SPEED_X = 300
BALL_SPEED_Y = -300
BALL_COLOR = (0,0,0)

# для блока
BLOCK_WIDTH = 25
BLOCK_HEIGHT = 20
COLOR_BLOCK = (0,0,0)
BLOCK_SPACING = 3
BLOCK_TOP_OFFSET = 10
BLOCK_LEFT_OFFSET = 5
BLOCK_COLS = (WIDTH - 2 * BLOCK_LEFT_OFFSET)  // (BLOCK_WIDTH+BLOCK_SPACING)

width = BLOCK_COLS * BLOCK_WIDTH + BLOCK_SPACING * (BLOCK_COLS-1) + 2 * BLOCK_LEFT_OFFSET
if width > WIDTH:
    BLOCK_COLS -= 1
    width = BLOCK_COLS * BLOCK_WIDTH + BLOCK_SPACING * (BLOCK_COLS - 1) + 2 * BLOCK_LEFT_OFFSET
BLOCK_LEFT_OFFSET = (WIDTH - (width - 2 * BLOCK_LEFT_OFFSET)) // 2

BLOCK_ROWS =  HEIGHT//3 // (BLOCK_HEIGHT+BLOCK_SPACING)

