# размеры окна
WIDTH = 800
HEIGHT = 600


# фпс
FPS = 60


# для текста
TEXT_COLOR = (0,0,0)
FONT_SIZE_TO_MAIN = 60
TEXT_SIZE_TO_SHORTCUT_KEYS = 30
TEXT_X_MAIN_TEXT = 0
TEXT_Y_MAIN_TEXT = 0
TEXT_X_SHORTCUT_KEYS = 20
TEXT_Y_SHORTCUT_KEYS_PAUSE = 20
TEXT_Y_SHORTCUT_KEYS_RESTART = 90



# для платформы
PLATFORM_COLOR = (0,0,0)
PLATFORM_WIDTH = 100
PLATFORM_HEIGHT = 10
PLATFORM_SPEED = 360
PLATFORM_BUTTOM_OFFSET = 20


# для мячей
BALL_RADIUS = 10
BALL_SPEED_X = 300
BALL_SPEED_Y = -300
BALL_COLOR = (0,0,0)
BALL_COLOR2 = (255,0,0)


# для блоков
BLOCK_WIDTH = 25
BLOCK_HEIGHT = 20
COLOR_BLOCK = (0,0,0)
BLOCK_SPACING = 3
BLOCK_TOP_OFFSET = 10
BLOCK_LEFT_OFFSET = 5
BLOCK_COLS = (WIDTH - 2 * BLOCK_LEFT_OFFSET)  // (BLOCK_WIDTH+BLOCK_SPACING)

width = BLOCK_COLS * BLOCK_WIDTH + BLOCK_SPACING * (BLOCK_COLS-1) + 2 * BLOCK_LEFT_OFFSET
if width > WIDTH:
    BLOCK_COLS -= 1
    width = BLOCK_COLS * BLOCK_WIDTH + BLOCK_SPACING * (BLOCK_COLS - 1) + 2 * BLOCK_LEFT_OFFSET
BLOCK_LEFT_OFFSET = (WIDTH - (width - 2 * BLOCK_LEFT_OFFSET)) // 2

BLOCK_ROWS =  HEIGHT // 3 // (BLOCK_HEIGHT+BLOCK_SPACING)


# для кнопок
BUTTON_COLOR = (107,143,221)
BUTTON_HEIGHT = 60
BUTTON_WIDTH = 200
BUTTON_X = WIDTH // 2 - 100
BUTTON_START_Y = HEIGHT // 3
BUTTON_START_CLS_Y = BUTTON_START_Y + 80
BUTTON_HOT_KEYS_Y = BUTTON_START_CLS_Y + 80
BUTTON_BACK_X = 800 - BUTTON_WIDTH - 20
BUTTON_BACK_Y = 600 - BUTTON_HEIGHT - 20

BUTTON_SHORTCUT_KEY_WIDTH = 30
BUTTON_SHORTCUT_KEY_HEIGHT = 30
BUTTON_SHORTCUT_KEY_PAUSE_Y = 15
BUTTON_SHORTCUT_KEY_PAUSE_X = 600
BUTTON_SHORTCUT_KEY_RESTART_Y = 85
BUTTON_SHORTCUT_KEY_RESTART_X = 600






